# Encoding: UTF-8
project_name: u2fsign

before:
  hooks:
    # - go mod tidy
    # - go generate ./...
builds:
  - id: windows-amd64
    main: .
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    goos:
      - windows
    goarch:
      - amd64
    flags:
      - -mod=vendor
      - -trimpath
    ldflags:
      - -s -w
      - -X main.GitCommit={{.ShortCommit}}
      - -X main.ReleaseVer={{.Version}}
      - -X main.ReleaseDate={{.Date}}
  - id: darwin
    main: .
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
      - CXX=o64-clang++
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    flags:
      - -mod=vendor
      - -trimpath
    ldflags:
      - -s -w
      - -X main.GitCommit={{.ShortCommit}}
      - -X main.ReleaseVer={{.Version}}
      - -X main.ReleaseDate={{.Date}}
  - id: linux
    main: .
    env:
      - CGO_ENABLED=1
    goos:
      - linux
    goarch:
      - amd64
      # - arm64
    flags:
      - -mod=vendor
      - -trimpath
    ldflags:
      - -s -w
      - -X main.GitCommit={{.ShortCommit}}
      - -X main.ReleaseVer={{.Version}}
      - -X main.ReleaseDate={{.Date}}

archives:
  - name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
      - goos: windows
        format: zip
    files:
      - ONLY_BINARY*

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
    - Merge pull request
    - Merge branch

release:
  # disable: true

signs:
  # - artifacts: checksum
  # - artifacts: all
